services:
  postgres:
    image: postgres:16
    container_name: job-portal-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: job_portal_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - job_portal_postgres_data:/var/lib/postgresql/data

volumes:
  job_portal_postgres_data: