##spring.jpa.hibernate.ddl-auto=update
#spring.sql.init.data-locations=classpath:sql/jobportalapi-data.sql
#spring.sql.init.schema-locations=classpath:sql/jobportalapi-schema.sql


spring.application.name=job-portal-api
logging.pattern.console=${CONSOLE_LOG_PATTERN:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %cyan(%msg%n)}
spring.datasource.url=jdbc:h2:file:./data/h2_jobportaldb;AUTO_SERVER=true
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.show-sql=${SHOW_SQL:true}
spring.h2.console.enabled=true
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.format_sql=true
spring.h2.console.path=/h2-console
spring.jpa.defer-datasource-initialization=true
spring.sql.init.data-locations=classpath:sql/jobportalapi-data.sql